@startuml
class Main{
 + static void main(String[] args)
}

class Bank{
 - String name
 - List<Customer> customers
 - List<String> listOfActions
 - Customer selectedCustomer
 + Bank(String)
 + void addCustomer(Customer)
 + Customer getCustomerById(int)
 + List<Customer> getCustomers()
 + List<String> getCustomersAsStrings()
 + void runCreateCustomersDialog()
 + void runDialog()
 + String toString()
}

class Customer{
 - String name
 - double balance
 + Customer(String, double)
 + void addToBalance(double)
 + void setBalance(double)
 + String toString()

}



Main *-- Bank
Bank *-- Customer

@enduml